---
name: Alec Hansed
bio: Hi! My name is Alec and I'm all about clean code, DevOps and agile software development. Scrum master, project owner and open-source contributor.
profile_pic_path: uploads/profile_pic.jpeg
address: 78869 Esker Plaza
city: Kolwezi
phone: 879-571-9633
email: ahansed0@bbb.org
