<?php

// Load autoload file generated by Composer.
require_once "vendor/autoload.php";

// Constant path of upload directory.
$UPLOAD_DIR = "uploads/";

// Constant path of configuration file.
$CONFIG_PATH = 'config.yaml';

// Load configuration file. This acts as the site's database.
$config = Spyc::YAMLLoad($CONFIG_PATH);
